// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using idp_mysql.IdentityUserStore;

namespace idp_mysql.Data.Migrations.IdentityServer.UserDb
{
    [DbContext(typeof(UserStoreDbContext))]
    partial class UserStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("idp_mysql.IdentityUserStore.IdentityUser", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProviderName")
                        .HasColumnType("longtext");

                    b.Property<string>("ProviderSubjectId")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SubjectId");

                    b.ToTable("identityUser");
                });

            modelBuilder.Entity("idp_mysql.IdentityUserStore.IdentityUserClaim", b =>
                {
                    b.Property<string>("ClaimId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserSubjectId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ClaimId");

                    b.HasIndex("UserSubjectId");

                    b.ToTable("identityUserClaim");
                });

            modelBuilder.Entity("idp_mysql.IdentityUserStore.IdentityUserClaim", b =>
                {
                    b.HasOne("idp_mysql.IdentityUserStore.IdentityUser", "IdentityUser")
                        .WithMany("IdentityUserClaims")
                        .HasForeignKey("UserSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("idp_mysql.IdentityUserStore.IdentityUser", b =>
                {
                    b.Navigation("IdentityUserClaims");
                });
#pragma warning restore 612, 618
        }
    }
}
